#!/bin/bash

# Вывод меню с иконками (Nerd Fonts) и обработка выбора
echo -e " Выключение\n Перезагрузка\n Выход" | wofi --dmenu --prompt="Выберите действие:" --hide-scroll --hide-search --width 500 --height 120 | {
    read choice
    case "$choice" in
        *"Выключение")
            systemctl poweroff
            ;;
        *"Перезагрузка")
            systemctl reboot
            ;;
        *"Выход")
            swaymsg exit
            ;;
        *)
            echo "Неверный выбор"
            ;;
    esac
}
