XCURSOR_SIZE=24

QT_QPA_PLATFORMTHEME=qt6ct
QT_QPA_PLATFORM=wayland;xcb
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
QT_AUTO_SCREEN_SCALE_FACTOR=1

MOZ_ENABLE_WAYLAND=1

GDK_SCALE=1
GTK_DECORATION_LAYOUT=:

ELECTRON_OZONE_PLATFORM_HINT=auto

CLUTTER_BACKEND=wayland

XDG_SESSION_TYPE=wayland
