# Shell variables
# Generated by 'wal'
wallpaper="{{image}}"

# Special
background='{{colors.background.default.hex}}'
foreground='{{colors.on_background.default.hex}}'
cursor='{{colors.on_background.default.hex}}'

# Colors
color0='{{colors.background.default.hex}}'
color1='{{colors.error.default.hex}}'
color2='{{colors.tertiary.default.hex}}'
color3='{{colors.primary_container.default.hex}}'
color4='{{colors.secondary.default.hex}}'
color5='{{colors.primary.default.hex}}'
color6='{{colors.surface_variant.default.hex}}'
color7='{{colors.on_background.default.hex}}'
color8='{{colors.outline_variant.default.hex}}'
color9='{{colors.error.default.hex}}'
color10='{{colors.tertiary.default.hex}}'
color11='{{colors.primary_container.default.hex}}'
color12='{{colors.secondary.default.hex}}'
color13='{{colors.primary.default.hex}}'
color14='{{colors.surface_variant.default.hex}}'
color15='{{colors.on_background.default.hex}}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
