[config.wallpaper]
command = "swww"
arguments = ["img"]
set = true

[templates.waybar]
input_path = '~/.config/matugen/templates/matugen-waybar.css'
output_path = '~/.config/waybar/colors.css'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.kde_colors]
input_path = '~/.config/matugen/templates/kde/color.txt'
output_path = '~/.local/state/quickshell/user/generated/color.txt'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/generated.conf'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/generated.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/your-theme.conf'
post_hook = 'kitty +kitten themes --reload-in=all your-theme'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.mako]
input_path = '~/.config/matugen/templates/mako-conf'
output_path = '~/.config/mako/config'
post_hook = 'makoctl reload'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/config'

[templates.walcolors_css]
input_path = '~/.config/matugen/templates/walcolors.css'
output_path = '~/.cache/wal/colors.css'

[templates.walcolors]
input_path = '~/.config/matugen/templates/walcolors'
output_path = '~/.cache/wal/colors'

[templates.wal]
input_path = '~/.config/matugen/templates/wal'
output_path = '~/.cache/wal/wal'

[templates.walcolors_sh]
input_path = '~/.config/matugen/templates/walcolors.sh'
output_path = '~/.cache/wal/colors.sh'
post_hook = 'walogram -s'

[templates.sway]
input_path = '~/.config/matugen/templates/sway-colors.conf'
output_path = '~/.config/sway/colors.conf'
post_hook = 'swaymsg reload'

[templates.ytm_css]
input_path = "~/.config/matugen/templates/ytm.css"
output_path = "~/.cache/ytm-colors.css"
post_hook = 'sh /home/naku/.config/matugen/hooks/ytm-post_hook.sh'
